// examples/tanstack-start/src/components/examples/FormDemo.tsx
import { useState } from 'react'
import { FkFormRender } from '@streamline-pulse/formkrafter-react'
import '@streamline-pulse/formkrafter-wc/styles.css'

import { m } from '#/paraglide/messages'
import { useLocale } from '#/components/LocaleProvider'

import type { BrickSpec, ValidationResult } from '@streamline-pulse/formkrafter-core'
import type { DataChangeDetail } from '@streamline-pulse/formkrafter-wc'

interface FormDemoProps {
  spec: BrickSpec
  data?: Record<string, unknown>
  context?: Record<string, unknown>
  localeOverride?: string
  showValidate?: boolean
}

export default function FormDemo({
  spec,
  data,
  context,
  localeOverride,
  showValidate = true,
}: FormDemoProps) {
  const { locale } = useLocale()
  const [verdict, setVerdict] = useState<ValidationResult>()
  const [submitted, setSubmitted] = useState<DataChangeDetail>()

  return (
    <div className="space-y-4">
      <form id="fk-demo" className="border-border bg-card rounded-lg border p-4">
        <FkFormRender
          spec={spec}
          locale={localeOverride ?? locale}
          data={data}
          context={context}
          onValidityChange={(event) => setVerdict(event.detail)}
          onFormSubmit={(event) => setSubmitted(event.detail)}
        />
      </form>

      {showValidate ? (
        <div className="flex items-center gap-3">
          <button
            type="submit"
            form="fk-demo"
            disabled={!verdict?.valid}
            className="bg-primary text-primary-foreground rounded-md px-4 py-2 text-sm font-semibold hover:opacity-90 disabled:cursor-not-allowed disabled:opacity-50"
          >
            {m.demo_validate()}
          </button>
          {verdict ? (
            <p
              className={
                verdict.valid
                  ? 'text-sm font-medium text-emerald-600 dark:text-emerald-400'
                  : 'text-destructive text-sm font-medium'
              }
            >
              {verdict.valid
                ? m.demo_valid()
                : m.demo_invalid({ count: Object.keys(verdict.errors).length })}
            </p>
          ) : null}
        </div>
      ) : null}

      {submitted ? (
        <section className="space-y-2">
          <h2 className="text-sm font-semibold">{m.demo_payload()}</h2>
          <pre className="border-border max-h-56 overflow-auto rounded-lg border bg-slate-900 p-3 text-xs text-slate-100">
            {JSON.stringify(submitted, null, 2)}
          </pre>
        </section>
      ) : null}
    </div>
  )
}

// examples/vue/src/FormDemo.vue
<script setup lang="ts">
import { ref, shallowRef } from 'vue'
import { FkFormRender } from '@streamline-pulse/formkrafter-vue'
import type { BrickSpec, ValidationResult } from '@streamline-pulse/formkrafter-core'
import type { DataChangeDetail } from '@streamline-pulse/formkrafter-wc'

const props = defineProps<{
  spec: BrickSpec
  locale?: string
  /** The stepper emits formSubmit itself, so its demo hides the button. */
  showValidate?: boolean
}>()

const data = shallowRef<Record<string, unknown>>({})
const verdict = shallowRef<ValidationResult>()
const submitted = shallowRef<Record<string, unknown>>()

/**
 * A template ref on a Stencil-generated Vue component yields the Vue
 * instance, not the custom element — the component's methods live on `$el`.
 */
const renderer = ref<{ $el: { validate: () => Promise<ValidationResult> } } | null>(null)

async function validate() {
  verdict.value = await renderer.value?.$el.validate()
}
</script>

<template>
  <div class="demo">
    <div class="demo__form">
      <FkFormRender
        ref="renderer"
        :spec="props.spec"
        :locale="props.locale"
        @form-data-change="data = ($event as CustomEvent<DataChangeDetail>).detail.data"
        @form-submit="submitted = ($event as CustomEvent<DataChangeDetail>).detail.data"
      />

      <button
        v-if="props.showValidate !== false"
        type="button"
        class="primary"
        data-testid="validate"
        @click="validate"
      >
        Validate
      </button>
    </div>

    <div class="demo__state">
      <p class="label">Live data</p>
      <pre data-testid="data">{{ JSON.stringify(data, null, 2) }}</pre>

      <p class="label">Verdict</p>
      <pre data-testid="verdict">{{ verdict ? JSON.stringify(verdict, null, 2) : '—' }}</pre>

      <p class="label">Submitted</p>
      <pre data-testid="submitted">{{ submitted ? JSON.stringify(submitted, null, 2) : '—' }}</pre>
    </div>
  </div>
</template>
